### ISSUE TITLE
Parser Error with Parenthetical size-arith

### ISSUE THREAD

**Issue by InnPatron** [RedlineResearch/floorplan#1]
Built with latest master.

flp fails to compile the following (a simplified snippet taken from the pre-print):

```
Foo -> (1 words - 1 bytes)
```
with error:
```
flp: Parse error with remaining input: [TokenWords,TokenMinus,TokenNum 1, TokenBytes, TokenRParen]
...
Parser.hs:1325:17
```

**Comment by InnPatron** [comment]
Ah, I see the issue.

There is a rule `exponent -> '(' litArith ')'` which is the only rule for parsing for parenthetical arithmetic. However, `sizePrim` is not expected within `litArith`, causing an error.

Probably a simple fix of adding the rule `sizeArith -> '(' sizeArith ')'`

**Comment by cronburg** [comment]
Thanks for reporting this!
