### ISSUE TITLE
Consider bundling address.rs + mod.rs into a separate crate

### ISSUE THREAD

**Issue by InnPatron** [RedlineResearch/floorplan#2]
Code generation assumes address.rs and macros are in `super::*`

Bundling address.rs + macros into a separate crate allows for import code-gen to be reduced to `use flp_framework::*;` where the crate will be imported within the Rust project's `Cargo.toml`.

In addition, should one want to have multiple flp files in different directories, this change will also reduce code duplication and simplify build scripts.

See [this version of flp_framework](https://github.com/InnPatron/flp_framework) for an example of such a crate that works with the above code generation change.

**Comment by cronburg** [comment]
All set. I haven't published the crates (or the haskell project) yet, but those should be available soon, as well.
